### ISSUE TITLE
5 GHz setup antenna

### ISSUE THREAD

**Issue by wluxie** [SC-Robotics-2023/.github#14]

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/211220859-47e72375-2160-46c1-9d2d-12ad642f8ae3.png)

**Comment by austinlake04** [comment]
No more memes on in the documentation please. All the information should be clear and concise.

**Comment by wluxie** [comment]
[isaac_ros_compression](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_compression)

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/220183994-851fd6f2-d93f-4f35-86c5-d3b1a6267dbf.png)
