### ISSUE TITLE
Begin autonomy-loop development.

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/.github#29]
Creation of behavior tree. Nav2 kinda looks useful. Need to do more research.
Start with GPS, build upon as Brooks was saying.

Terms to research:
- PID Loop

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/220184492-b991ca17-6f5b-496b-834d-25762b0be71c.png)

**Comment by Supernova1114** [comment]
Aruco detection and movement towards tag is working.

Awesome job @camwolff02 

GPS is working.
Nav X is working.
LIDAR is working.

We will be using Nav2 and Gazebo.
