### ISSUE TITLE
Test 5GHz

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/.github#42]
Notes from board:
- Try the bullet AC 5GHz again.
- Virtualize it (?)

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/227641508-ae5a0c8b-e492-4e82-a319-a5d1fbe6f258.png)

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/227641647-48fae36c-8d61-4ef6-9ae3-510701758a23.png)
