### ISSUE TITLE
Data Compression

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/.github#45]
Research to see if we can use a general purpose library or command line tool for data compression.
- Data to be sent to and from Rover.
- Higher priority, we need a good method for image compression.
- Something that is modular. And easily usable for other systems.
- For images we may be able to use hardware accelerated compression. (Uses Jetson GPU.)
- If we do use an implementation of hardware accel compression, would like to also have an implementation of normal compression.
- Easy to access variables for compression amount.

- A function that can be passed an image and it will return a compressed one?

**Comment by wluxie** [comment]
We passed the deadline for this. Let's remove @mcdipples as the assignees and move on with another plan in mind

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/233801418-fce7b705-84ff-4b73-a2f0-6f75c03bb562.png)
