### ISSUE TITLE
Migrate Ymir to Ubuntu Server

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/.github#46]
- Reflash Ymir to Ubuntu Server
- Set up static IP for Ymir

**Comment by wluxie** [comment]
![Image](https://user-images.githubusercontent.com/49565505/231680130-67167410-b552-401f-b5e6-cd244a23a22a.png)

**Comment by wluxie** [comment]
Ymir is reflashed with Ubuntu and an IP-address attached to it. @Gryuuum never got around it so I took over
