### ISSUE TITLE
Improve turret/funnel-cake code

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/.github#52]
I wrote prototype code for funnel-cake movement. Needs to be improved.

<br>

The issue with it right now is that you have to manually input an encoder value for it to travel to. Would like to label each funnel with a number, and be able to input that number for it to rotate to. i.e. The number corresponds to an individual funnel, the funnel location has a specific encoder value.

<br>

Would like to make sure that we have capability to do small positioning tweaks if needed.
Remind me to remove the turret rotation limits from the motor controller.

**Comment by wluxie** [comment]
Closed, opened new issue
