### ISSUE TITLE
General Telecom Tasks

### ISSUE THREAD

**Issue by camwolff02** [SC-Robotics-2023/.github#77]
- [x] Switch compression to hardware encoding
- [x] Have working backup compression to use on PI
- [x] Fix dark screen/Vertical lines (could be loose cable issue)
- [x] Fix latency issues (3-15s of latency currently)
- [x] Improve resolution (stretch goal)
- [x] Improve bandwidth usage
- [ ] Finalize operator camera feed views
- [x] Finalize method for switching between camera views
- [ ] Switch to new build system and create 2 launch files
- [ ] Add on the fly resolution / fps switching (Stretch goal)
- [ ] High Quality snapshot request (any cam)

**Comment by Supernova1114** [comment]
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_compression

https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline
